# Generated by Django 5.0.1 on 2024-01-13 08:12

from django.db import migrations


def create_blog(apps, schema_editor):
    for i in range(1, 10):
        Blog = apps.get_model('website', 'Blog')
        Blog.objects.create(title=f'Title {i}', content=f'Content {i}')


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_blog),
    ]
